# Generated by Django 5.1.6 on 2025-03-03 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('task_object', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('user_type', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('access_right_Tasks', models.BooleanField(default=False)),
                ('access_right_Modules', models.BooleanField(default=False)),
                ('access_right_Self', models.BooleanField(default=False)),
                ('access_right_other_users', models.BooleanField(default=False)),
                ('edit_right_modules', models.BooleanField(default=False)),
                ('edit_right_tasks', models.BooleanField(default=False)),
                ('edit_right_user_premissions', models.BooleanField(default=False)),
                ('edit_right_self', models.BooleanField(default=False)),
                ('edit_right_other_user', models.BooleanField(default=False)),
                ('delete_right_tasks', models.BooleanField(default=False)),
                ('delete_right_modules', models.BooleanField(default=False)),
                ('delete_right_self', models.BooleanField(default=False)),
                ('delete_right_other_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.userpermission')),
            ],
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('user', 'task')},
            },
        ),
    ]
