# Generated by Django 5.1.6 on 2025-03-20 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userquizscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('reward_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('points_required', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.CreateModel(
            name='QuizBlokkOppgave',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('quiz_blokk_data', models.JSONField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.module')),
            ],
        ),
        migrations.CreateModel(
            name='UserRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_awarded', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rewards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('user', 'reward')},
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oppgave_name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('best_score', models.IntegerField()),
                ('finished', models.BooleanField()),
                ('attempts', models.IntegerField()),
                ('last_attempt', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quizblokkoppgave')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('user', 'task')},
            },
        ),
        migrations.DeleteModel(
            name='UserModule',
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
