# Generated by Django 5.1.7 on 2025-03-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Nybegynner'), ('intermediate', 'Viderekommen'), ('advanced', 'Avansert')], default='beginner', max_length=20),
        ),
    ]
