# Generated by Django 5.1.7 on 2025-04-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
